### ISSUE TITLE
Section 1 - Subsection 1.4 Product Scope

### ISSUE THREAD

**Issue by gagefulwood** [citlalih1421/Group3-SE#7]
Provide a short description of the software being specified and its purpose, including relevant benefits, objectives, and goals. Relate the software to corporate goals or business strategies. If a separate vision and scope document is available, refer to it rather than duplicating its contents here.

**Comment by yas27s** [comment]
1.4 Product Scope 

The web application [BLANK] provides the consumer with a hub that other consumers use to buy, sell, and trade goods (primarily shoes). The reason for this application is to provide users with a database of goods sold by other consumers providing a convenient way to shop as well as a place to sell goods at a price of your choosing. Keeping up with modern standards this platform will allow users to filter through content through various forms of characterization such as type, color, and size. This also provides the opportunity for people to sell their goods on our platform through our user-friendly design that makes setting up the listing easy and simple to do.

This design makes it so that the software and its features are as simple as an average consumer scrolling through finding an item and adding it to cart or adding a listing waiting for an offer and allow our platform to be a place for the goods to be widely viewed by a large audience to be purchased. In more detail, as a user sequentially you will make an account with a user and password and log in. Then you can search through our platform with tools to help your search such as filtering through items by type, color, or size. Say you found an item you can simply add it to your cart and finish the process by checking out. Now for the seller, it’s the same simple process just with a couple more features to make listing their item not a problem. The process prompts the user with questions about this product to then translate the filtering process in our system to seamlessly categorize it to the user's desired specs. When those questions are answered they will list the item and wait for offers or trades to arrive in their inbox so that they may weigh their options. 

Provided that users decide to sell their goods the domain owners will take a small commission to provide them with continuous support through keeping the life span of the web application going and to make sure this doesn’t shy the user away from selling their goods this fee will be relatively low to keep the user base happy and encourage them to exchange their goods on the platform. By keeping these fees low ads relative to the user's search will be implemented to maintain the quality and reliability of the website alongside the developer and investors' continuous support of the application. 



(ChatGPT version):

The web application, [BLANK], serves as a hub for consumers to buy, sell, and trade goods, primarily shoes. The purpose of this application is to provide users with a database of goods sold by other consumers, offering a convenient shopping experience and a platform to sell goods at a user-defined price. Aligning with modern standards, the platform enables users to filter content based on various characteristics such as type, color, and size.

The user-friendly design facilitates easy listing setup, allowing individuals to showcase their goods to a broad audience. The software's simplicity ensures a seamless experience for both buyers and sellers, where buyers can easily add items to their carts, and sellers can list items and await offers or trades in their inbox.

To start using the platform, users create an account with a username and password, followed by a login. The search tools, including filters for type, color, and size, assist users in finding items efficiently. Once a desired item is found, it can be added to the cart and purchased with a straightforward checkout process. Sellers follow a similar process, answering questions about their product to categorize it effectively, then listing the item and waiting for offers or trades.

In the event users decide to sell their goods, the domain owners will impose a modest commission to support the continuous development of the web application. This fee aims to maintain a positive user experience and encourage users to participate in exchanges on the platform. To offset the low fees, relevant ads will be implemented, ensuring the website's quality and reliability. Ongoing support from developers and investors will contribute to the application's longevity and success.

**Comment by gagefulwood** [comment]
Completed by Yusuf
